---
- name: Install Java
  become: true
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Copy Producer JAR file
  become: true
  ansible.builtin.copy:
    src: /app/Producer/Producer.jar
    dest: /opt/Producer.jar
    mode: 0644

- name: Unzip jar file
  become: true
  ansible.builtin.unarchive:
    src: /opt/Producer.jar
    dest: /opt
    remote_src: true

- name: Run Producer Java application
  become: true
  ansible.builtin.command: "nohup java -cp /opt Main &"
  async: 45
  poll: 0