---
#- name: Install Java
#  apt:
#    name: openjdk-11-jdk
#    state: present
#    update_cache: yes
#  become: true

- name: Copy Producer JAR file
  copy:
    src: /app/Producer/Producer.jar
    dest: /opt/Producer.jar
    mode: 0644
  become: true

- name: Unzip jar file
  ansible.builtin.unarchive:
    src: /opt/Producer.jar
    dest: /opt
    remote_src: true
  become: true

#- name: Run Producer Java application
#  command: "java -cp /opt Main &"
#  become: true