---
#- name: Install Java
#  apt:
#    name: openjdk-11-jdk
#    state: present
#    update_cache: yes
#  become: true

- name: Copy Producer JAR file
  copy:
    src: /app/Producer/Producer.jar
    dest: /opt/Producer.jar
    mode: 0644
  become: true

- name: Run Producer Java application
  command: "java -jar /opt/Producer.jar &"
  become: true