---
- name: Install Java
  become: true
  apk:
    name: openjdk-11-jdk
    state: present

- name: Copy Producer JAR file
  copy:
    src: /app/ISD_BIT_Lab3/Producer/Producer.jar
    dest: /opt/Producer.jar
    mode: 0644
  become: true

- name: Run Java application
  command: >
    java -jar /opt/Producer.jar
  become: true
