---
- name: Install Java
  become: true
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Copy Consumer JAR file
  become: true
  copy:
    src: /app/Consumer/Consumer.jar
    dest: /opt/Consumer.jar
    mode: 0644

- name: Unzip jar file
  become: true
  ansible.builtin.unarchive:
    src: /opt/Consumer.jar
    dest: /opt
    keep_newer: true
    remote_src: true

- name: Run Consumer Java application
  become: true
  command: "nohup java -cp /opt:/opt/mysql-connector-java-8.0.30.jar Main &"
  async: 45
  poll: 0