---
#- name: Install Java
#  apt:
#    name: openjdk-11-jdk
#    state: present
#    update_cache: yes
#  become: true

- name: Copy Consumer JAR file
  copy:
    src: /app/Consumer/Consumer.jar
    dest: /opt/Consumer.jar
    mode: 0644
  become: true

- name: Unzip jar file
  ansible.builtin.unarchive:
    src: /opt/Consumer.jar
    dest: /opt
    keep_newer: true
    remote_src: true
  become: true

#- name: Run Consumer Java application
#  command: "java -cp /opt:/opt/mysql-connector-java-8.0.30.jar Main &"
#  become: true