---
#- name: Install Java
#  apt:
#    name: openjdk-11-jdk
#    state: present
#    update_cache: yes
#  become: true

- name: Copy Consumer JAR file
  copy:
    src: /app/Consumer/Consumer.jar
    dest: /opt/Consumer.jar
    mode: 0644
  become: true
#
#- name: Run Consumer Java application
#  command: "java -jar /opt/Consumer.jar &"
#  become: true