FROM alpine:3.11

RUN apk add --no-cache openssh-client openssh-server ansible git sshpass \
    && mkdir -p /root/.ssh \
    && echo "HOST *" > /root/.ssh/config && echo " StrictHostKeyChecking no" >> /root/.ssh/config \
    && ansible-galaxy collection install community.mysql

COPY ./ansible .
COPY ./app /app

RUN echo "" > .my.chf \
    && echo "[client]\n" >> .my.cnf \
    && echo "user=root\n" >> .my.cnf \
    && echo "password=root" >> .my.cnf

CMD [""]