FROM ubuntu:14.04

RUN apt-get update \
    && apt-get install -y openssh-server python3 python3-pip

RUN awk '{ sub(/#PermitRootLogin prohibit-password/, "PermitRootLogin yes"); } 1' /etc/ssh/sshd_config > /tmp/sshd_config \
    && mv /tmp/sshd_config /etc/ssh/sshd_config \
    && echo "root:root" | chpasswd \
    && adduser --disabled-password --gecos "" user && echo "user:password" | chpasswd \
    && sudo usermod -aG sudo user \
    && echo "user ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers \
    && echo "sudo ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers \
    && service ssh restart

CMD ["/usr/sbin/sshd","-D"]