---
- name: Install required packages
  apt:
    name:
      - python-mysqldb
      - mysql-server
    update_cache: yes
    state: present
  become: true

- name: Enable and start mysql
  service:
    name: mysql
    state: started
    enabled: yes
  become: true

#- name: Copy .my.cnf
#  copy:
#    src: .my.cnf
#    dest: /root/.my.cnf
#    mode: 0644
#  become: true

- name: Update MySql root password
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    host: "localhost"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  become: true

- name: Create MySQL user
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    state: present
  become: true

- name: Create MySql db
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    name: "{{ mysql_database }}"
    state: present
  become: true

- name: Create table in MySQL database
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    db: "{{ mysql_database }}"
    query: "CREATE TABLE IF NOT EXISTS {{ mysql_table }} (timestamp VARCHAR(255) PRIMARY KEY, jsoned_object VARCHAR(1023));"
  become: true
  notify: Restart MySQL