---
- name: Install required packages
  apt:
    name:
      - pip
      - mysql-server
      - default-libmysqlclient-dev
    update_cache: yes
  become: true

- name: Install mysql python library
  pip:
    name: mysqlclient
  become: true

- name: Enable and start mysql
  service:
    name: mysql
    state: started
    enabled: yes
  become: true

- name: Waiting for MySQL Service
  wait_for:
    port: 3306
    delay: 5
  become: true

- name: Creating MySql db
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
  become: true

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
  become: true

- name: Create table in MySQL database
  community.mysql.mysql_query:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    db: "{{ mysql_database }}"
    query: "CREATE TABLE IF NOT EXISTS {{ mysql_table }} (timestamp VARCHAR(255) PRIMARY KEY, jsoned_object VARCHAR(1023));"
  become: true