---
#- name: Gather Facts and Display Information
#  hosts: all
#  gather_facts: true
#  tasks:
#    - name: Display Gathered Facts
#      debug:
#        var: ansible_facts

- name: my_sql setup
  hosts: name_server_db
  roles:
    - my_sql
  become: true

- name: Install and Run Consumer Application
  hosts: name_server_consumer
  roles:
    - application_consumer
  become: true

- name: Install and Run Producer Application
  hosts: name_server_producer
  roles:
    - application_producer
  become: true